export const GET_ERRORS='GET_ERRORS';
export const CLEAR_ERRORS='CLEAR_ERRORS'
export const SET_CURRENT_USER='SET_CURRENT_USER';

export const ADD_PRODUCER='ADD_PRODUCER'
export const GET_PRODUCER='GET_PRODUCER'
export const DELETE_PRODUCER='DELETE_PRODUCER'
export const LOADING_PRODUCER='LOADING_PRODUCER'

export const ADD_PRODUCT='ADD_PRODUCT'
export const GET_PRODUCT='GET_PRODUCT'
export const DELETE_PRODUCT='DELETE_PRODUCT'
export const DELETE_IMAGE_PRODUCT='DELETE_IMAGE_PRODUCT'
export const LOADING_PRODUCT='LOADING_PRODUCT'

export const GET_PRODUCTS='GET_PRODUCTS'
export const LOADING_PRODUCTS='LOADING_PRODUCTS'

export const GET_CART='GET_CART'
export const ADD_TO_CART='ADD_TO_CART'
export const UPDATE_CART='UPDATE_CART'
export const DELETE_CART_ITEM='DELETE_CART_ITEM'
export const CLEAR_CART='CLEAR_CART'

export const SEARCH='SEARCH'
export const ORDER='ORDER'